config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :tasks

  root 'records#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :records
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    # Praktično nova instanca metode new
    @record = Record.new
    # Naredna linija koda čini mi dostupnim Task model radi čitanja ID-a
    @tasks = Task.all
  end

  def create
    @record = Record.new(recordparams)

    if @record.save
      redirect_to root_path()
    else
      render :new
    end
  end

  def show
    record_id = params[:id]
    @record = Record.find(record_id)
    @task = Task.where(id: params[:id])
  end

  def recordparams
    params.require(:record).permit(:begintime, :endtime, :difftime, :taskid, :recorddate)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(taskparams)

    if @task.save
      redirect_to root_path()
    else
      render :new
    end
  end

  def show
    task_id = params[:id]
    @task = Task.find(task_id)
    @records = Record.all.where(taskid: params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    task_name = @task.taskname
    if @task.update_attributes(taskparams)
      flash[:notice] = "Zadatak pod naslovom -| #{task_name} |- ažuriran!"
      redirect_to root_path()
    else
      render :edit
    end

  end

  def destroy
    @task = Task.find(params[:id])
    task_name = @task.taskname
    @task.destroy()
    flash[:notice] = "Zadatak pod naslovom -| #{task_name} |- obrisan!"
    redirect_to root_path()
  end



  def taskparams
    params.require(:task).permit(:taskname, :clientname, :taskstatus, :taskdesc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebWaqtar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- ### ### ### jQuery library ### ### ### -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- ### ### ### jQuery UI library ### ### ### -->
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" />

  <!-- ### ### ### Bootstrap 3 ### ### ### -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap-theme.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/npm.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.js"></script>

<!-- ### ### ### Font Awesome icons ### ### ### -->
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

<!-- ### ### ### Source Sans Pro Google Fonts ### ### ### -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900&subset=latin-ext" rel="stylesheet">


</head>
<body>
  <header>
  <div class="container-fluid header-cover">
    <div class="container">
      <h1 style="text-shadow: 1px 1px #000"><i class="fa fa-clock-o" aria-hidden="true"></i> WEB WAQTAR</h1>
      <p>Ruby on Rails aplikacija za obračun radnog vremena</p>
      <p>Development & maintenance: Rusmir Gadžo</p>
      <p>&nbsp;</p>
      <p>&raquo <%= link_to "Dodaj novi projekat", new_task_path(), alt: 'Dodaj novi projekat', title: 'Dodaj novi projekat' %>
        &raquo <%= link_to "Unesi novo vrijeme", new_record_path(), alt: 'Unesi radno vrijeme', title: 'Unesi radno vrijeme' %>
      </p>
      <!-- <p> <a class="link-blue" href="#" data-toggle="modal" data-target="#login-modal-win" id="login-modal-btn">LOGIN</a> </p> -->
    </div>
  </div>
  <div class="container-fluid" style="background-color:#333; color:#FFF;">
    <p class="text-center" style="margin:0px !important; padding:10px;">
      <% unless flash[:notice].nil? %>
      <%= flash[:notice] %>
      <% end %>
  </p>
  </div>
  </header>

<!--      WAQTAR: MODAL: ADD TASK     -->

        <!-- CSS Modal START -->
        <style>
        .modal-header, h4, .close {
        background-color: #000;
        color:white !important;
        text-align: center;
        font-size: 30px;
        }
        </style>
        <!-- CSS Modal END -->

<div class="container">
          <!-- Modal -->
          <div class="modal fade" id="login-modal-win" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header" style="padding:35px 50px;">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4>Dodaj novi projekat</h4>
                </div>
                <div class="modal-body" style="padding:40px 50px;">
                  <form role="form">
                    <div class="form-group">
                      <label for="usrname"><span class="glyphicon glyphicon-tasks"></span> Naziv projekta</label>
                      <input type="text" class="form-control" id="usrname" placeholder="...projekat">
                    </div>
                    <div class="form-group">
                      <label for="psw"><span class="glyphicon glyphicon-user"></span> Naručilac</label>
                      <input type="text" class="form-control" id="psw" placeholder="...naručilac">
                    </div>
                      <button type="submit" class="btn btn-block btn-warning" style="background-color:#FF8500; color:#FFF;"><span class="glyphicon glyphicon-plus-sign"></span> <strong>Dodaj projekat</strong></button>
                      <div style="height:5px;">&nbsp;</div>
                  </form>
                </div>

              </div>

            </div>
          </div>
</div>


<!--      WAQTAR: MODAL: ADD TASK     -->



<%= yield %>

<hr />

<footer>
  <div class="container">
    <h3>Changelog:</h3>
    <ul>
      <li>Uređivanje/izmjena zadatka</li>
      <li>Status zadatka - indikator i izmjena status</li>
    </ul>
  </div>
<footer>

<hr />

<div class="container-fluid text-center">
  <p class="btn-primary" style="padding:10px;">HTML 5 &bull; Bootstrap 3 &bull; Ruby on Rails &bull; jQuery &bull; PostgreSQL
<br>Hosted by: HEROKU </p>
</div>
<p>&nbsp;</p><p>&nbsp;</p>

</body>
</html>

app/views/records/index.html.erb
<div class="container">
  <table class="table">
  <thead>
    <tr>
      <td colspan="3"><h3>Lista aktuelnih projekata</h3></td>
    </tr>
    <tr>
      <td bgcolor="EAEAEA"><strong>Br.</strong></td>
      <td bgcolor="EAEAEA"><strong>Naslov projekta</strong></td>
      <td bgcolor="EAEAEA"><strong>Naručilac projekta</strong></td>
      <td bgcolor="EAEAEA" align="right">&nbsp;</td>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |zadatak| %>
       <% @task_status = zadatak.taskstatus %>
    <tr>
      <td><%= zadatak.id %></td>
      <td>
      <%= link_to task_path(id: zadatak.id) do %><%= zadatak.taskname %><% end %>
      <div class="task-description-index">
        <%= zadatak.taskdesc.truncate_words(8).html_safe %>
      </div>
      </td>
      <td><%= zadatak.clientname %></td>
      <td align="right">
      <% if @task_status == "status-task-open" %>
        <%= link_to edit_task_path(zadatak.id) do%>
          <%= image_tag('edit-task-tableicon', alt: "Izmijeni zadatak") %>
        <% end %>
      <% elsif @task_status == "status-task-locked" %>
      <%= image_tag('edit-task-tableicon', alt: "Izmijeni zadatak", class: "deactivate") %>
      <% end %>


      <% if @task_status == "status-task-open" %>
        <%= link_to new_record_path() do %>
              <%= image_tag('new-record-tableicon.png') %>
        <% end %>
      <% elsif @task_status == "status-task-locked" %>
        <%= image_tag('new-record-tableicon.png', class: "deactivate") %>
      <% end %>

      <%= link_to task_path(zadatak.id), method: :delete, :data => {:confirm => 'Sigurno želiš obrisati ovaj zadatak?'} do %>
          <%= image_tag('delete-task-tableicon', alt: "Izbriši zadatak") %>
      <% end %>

      <%= image_tag("#{@task_status}", size:'16x16') %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>

<div class="separator50">&nbsp;</div><div class="separator50">&nbsp;</div>

app/views/records/new.html.erb
<script>
$( function() {
  $("#record_recorddate").datepicker({ dateFormat: 'yy-mm-dd' });

 });

</script>


<div class="container">
  <h1 class="text-center"> Dodaj novi <span style="color:#FF0000;">vremenski unos</span> </h1>
  <p>&nbsp;</p>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for(@record) do |unos| %>
        <div class="form-group">
          <%= unos.label "Početak (HH:MM)" %>
          <%= unos.text_field :begintime, class: 'form-control', value: Time.now.strftime('%H:%M'), required: true %>
        </div>
        <div class="form-group">
          <%= unos.label "Kraj (HH:MM)" %>
          <%= unos.text_field :endtime, class: 'form-control', required: true %>
        </div>
        <script>
        $(document).ready(function(){

          function Timecount(){
            var starttime = $("#record_begintime").val();
            var finishtime = $("#record_endtime").val();

            var st_cut = starttime.split(':')
            var et_cut = finishtime.split(':')
            var sahat1 = parseInt(st_cut[0]);
            var minut1 = parseInt(st_cut[1]);
            var sahat2 = parseInt(et_cut[0]);
            var minut2 = parseInt(et_cut[1]);

            if (sahat2 > sahat1){
              if (sahat2-sahat1 == 1)
                min_total = (60-minut1) + minut2;
              else {
                min_total = (60-minut1) + minut2 + ((sahat2-sahat1-1)*60);
              }

            } else if (sahat2 == sahat1) {
              if (minut2 > minut1){
              // primjer 16:15 - 16:56
              min_total = minut2 - minut1;
              } else {
              min_total = 1440 - (minut1 - minut2);
              // !!! radni obim od skoro 24h... ???
              }
            } else {
              min_total = ((24-sahat1)*60-minut1) + ((sahat2*60)+minut2);
            }

            $("#record_difftime").val(min_total);

          }



          $("#record_difftime").click(
            function() {
              Timecount();
          });

          $(window).mouseover(function() {
            Timecount();
          });

        });

        </script>
        <button type="button" class="btn btn-danger" id="runner" style="display:none;">Danger</button>
        <div class="form-group">
          <%= unos.label "Ukupno minuta:" %>
          <%= unos.text_field :difftime, class: "form-control text-center time-diff-display", readonly: true, value: '000' %>
        </div>
        <div class="form-group">
          <p>&nbsp;</p>
          <%= collection_select(:record, :taskid, Task.all, :id, :taskname, {prompt: "Odaberi projekat"}, {class: "form-control", required: true}) %>
        </div>
        <div class="form-group">
          <%= unos.label "Datum unosa" %>
          <%= unos.text_field :recorddate, class: "form-control", required: true %>
        </div>
        <div class="form-group">
          <%= unos.submit "Dodaj unos!", class: "btn btn-large btn-success" %>
          <a href="<%= root_path %>" class="btn btn-warning" role="button">Poništi</a>
        </div>
      <% end %>

    </div>
  </div>

<div class="separator50">&nbsp;</div>

</div>

app/views/records/show.html.erb
<div class="container">
  <h1 class="text-center"> Prikaži odabrani <span style="color:#FF0000;">zadatak</span>: <br>
    <% @task.each do |ime_zadatka| %>
    <%= ime_zadatka.taskname %>
    <% end %> (<%= @record.id %>)</h1>
  <div class="row">
    <div class="col-md-6">
      <p><%= @record.begintime %></p>
      <p><%= @record.endtime %></p>
      <p><%= @record.difftime %></p>
    </div>
    <div class="col-md-6">
      <h3><%= @record.difftime %></h3>
    </div>
  </div>

<div class="separator50">&nbsp;</div>

<a href="<%= root_path %>" class="btn btn-warning text-center" role="button">Nazad na početnu</a>

<div class="separator50">&nbsp;</div>

</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="text-center">Izmjeni <span style="color:#FF0000"> zadatak</span></h1>

  <p>&nbsp;</p>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for(@task) do |zadatak|%>

        <div class="form-group">
          <%= zadatak.label "Naziv projekta" %>
          <%= zadatak.text_field :taskname, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= zadatak.label "Naručilac" %>
          <%= zadatak.text_field :clientname, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= zadatak.label "Status" %>
          <% zadatak_status = [['Otvoren zadatak', 'status-task-open'], ['Zaključan zadatak', 'status-task-locked']] %>
          <%= zadatak.select :taskstatus, zadatak_status, {}, { class: "form-control", required: true } %>
        </div>

        <div class="form-group">
          <% zadatak.label "Opis zadatka"%>
          <%= zadatak.text_area :taskdesc, :class => "tinymce", :rows => 10, :cols => 10 %>
        </div>

        <div class="form-group">
          <%= zadatak.submit "Izmjeni!", class: 'btn btn-success text-center btn-large' %>
          <a href="<%= root_path %>" class="btn btn-warning" role="button">Poništi</a>
        </div>

      <% end %>
    </div>
  </div>

</div>

<%= tinymce %>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="text-center">Dodaj novi <span style="color:#FF0000">projekat</span></h1>

  <p>&nbsp;</p>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for(@task) do |zadatak|%>

        <div class="form-group">
          <%= zadatak.label "Naziv projekta" %>
          <%= zadatak.text_field :taskname, class: 'form-control', required: true %>
        </div>

        <div class="form-group">
          <%= zadatak.label "Naručilac" %>
          <%= zadatak.text_field :clientname, class: 'form-control', required: true %>
        </div>

        <div class="form-group" style="visibility: hidden;">
          <%= zadatak.label "Status" %>
          <% zadatak_status = [['Otvoren zadatak', 'status-task-open']] %>
          <%= zadatak.select :taskstatus, zadatak_status, { class: "form-control", required: true, readonly: true } %>
        </div>

        <div class="form-group">
          <% zadatak.label "Opis zadatka"%>
          <%= zadatak.text_area :taskdesc, :class => "tinymce", :rows => 10, :cols => 10 %>
        </div>

        <div class="form-group">
          <%= zadatak.submit "Dodaj!", class: 'btn btn-success text-center btn-large' %>
          <a href="<%= root_path %>" class="btn btn-warning" role="button">Poništi</a>
        </div>

      <% end %>
    </div>
  </div>

</div>


<%= tinymce %>

app/views/tasks/show.html.erb
<div id="subHeader" style="background-color:#333; font-size:16px;">
<p class="text-center"><span style="color:#EAEAEA;"><i class="fa fa-quote-left fa-1x" aria-hidden="true"></i> <%= @task.taskname %> <i class="fa fa-quote-right fa-1x" aria-hidden="true"></i></span></p>
<p>&nbsp;</p>
</div>

<p>&nbsp;</p>
<div class="container">
  <div class="task-description-show"><%= @task.taskdesc.html_safe %></div>
</div>
<div class="separator50">&nbsp;</div>

<div class="container">
  <table class="table">
  <thead>
    <tr style="font-weight:700;">
      <td bgcolor="EAEAEA">Br.</td>
      <td bgcolor="EAEAEA">Datum unosa</td>
      <td bgcolor="EAEAEA">Početak:</td>
      <td bgcolor="EAEAEA">Kraj:</td>
      <td bgcolor="EAEAEA" align="right">Minutaža</td>
    </tr>
  </thead>
  <tbody>

      <% @show_count = 1; %>
      <% @total_mins = 0; %>
      <% @records.each do |unosi| %>
      <tr>
      <td> <%= @show_count %> </td>
      <td><%= unosi.recorddate %></td>
      <td><%= unosi.begintime %></td>
      <td><%= unosi.endtime %></td>
      <td align="right"><%= unosi.difftime %></td>
      <tr>
        <% @show_count += 1 %>
        <% @total_mins = @total_mins + unosi.difftime %>
      <% end %>
      <tr>
        <td align="left" class="total-mins-table">TOTAL:</td>
        <td align="right" colspan="4" class="total-mins-table">
          <%= @total_mins %> minuta | <span style="font-weight:100 !important;"><%= (@total_mins/60).to_i %> sati i <%= @total_mins - ((@total_mins/60).to_i*60) %> minuta</span></td>
      </tr>
  </tbody>

</table>


<div class="separator50">&nbsp;</div>
<a href="<%= root_path %>" class="btn btn-warning text-center" role="button">Nazad na početnu</a>
<div class="separator50">&nbsp;</div>
</div>